apiVersion: v1
kind: ServiceAccount
metadata:
  name: livekit-server
  namespace: call-center
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: livekit-egress
  namespace: call-center
  annotations:
    # Bind to GCP SA for GCS write access (Workload Identity)
    iam.gke.io/gcp-service-account: call-center-egress@hello-jade.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: livekit-agent
  namespace: call-center
